---
title: </font><font size="6"><br><b>OTS Tropical Biology 2023</b></font><br>
output: github_document
editor_options: 
  chunk_output_type: console
---

<!-- README.md is generated from README.Rmd. Please edit that file -->
<br>

<font size="5"><b><a href="https://tropicalstudies.org/">Organization for Tropical Studies</a><br></b></font><br>


<font size="4">Jun 14-15, 2023</font>

&nbsp; 

Traditionally, statistical models have been taught as disconnected tools with no clear relationship between them. However, most of those common statistical models are just special cases of linear models. Hence, learning them as such can largely simplify things. The course will focus on linear regression as the main tool for statistical inference. Students will be introduced to the basic elements of a linear regression model, its interpretation, as well as hands-on experience on building those models in R.


### Objectives

- Understand statistical inference through a single modelling tool (broad sense linear models)

- Get familiar with building linear models
 
- Extent linear models to different data structures

&nbsp; 

